import 'bootstrap/dist/css/bootstrap.css';
import './globals.css'
import Header from './Components/Header'




export const metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}) {
  return (
    
      <html lang="en">
        <body className='bg-black'>
          <Header />
            <main className='mt-20'>
                {children}
            </main>
        </body>
      </html>
    
  )
}